### ISSUE TITLE
redis' expiry is seconds not milli-seconds

### ISSUE THREAD

**Issue by jdalton** [npm/npm-explicit-installs#19]
See [npm/npm-explicit-installs/index.js#L91](https://github.com/npm/npm-explicit-installs/blob/75db3d38f3072edd5d9ffa031d6894f02bd633cc/index.js#L91).
It looks like it's caching it for 150,000 days.

Related to [npm/newww/issues/1946](https://github.com/npm/newww/issues/1946#issuecomment-224127549).

**Comment by nexdrew** [comment]
Oh, nice find, thanks!
