### ISSUE TITLE
Run the data crunch

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/npm-explicit-installs#3]
It looks like this list was last updated about 8 months ago: https://github.com/npm/npm-explicit-installs/commits/master/build.js

I struggle to believe there has been absolutely no change in which packages people are npm installing in the last 8 months.

[see also npm/newww#1374]

**Comment by bcoe** [comment]
@seldo do we want to update this list sometime soon? I think the ecosystem has changed a bit since we first pulled it.

**Comment by seldo** [comment]
We ran it again in October, after this comment, and got pretty much the same list: https://docs.google.com/a/npmjs.com/spreadsheets/d/120am_J_6g5WKI0ArzoaY3EsYiP_KL1LJrXpVVRoxknY/edit?usp=sharing

**Comment by bcoe** [comment]
@seldo :+1:
